KombniyAppAccount/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KombniyAppAccount.Models;
using KombniyApp.Core.Models;
using KombniyApp.Core.Services;

namespace KombniyAppAccount.Controllers
{
	public class GalleryController : Controller
	{
		private readonly IImage _imageService;

		public GalleryController(IImage ımage)
		{
			_imageService = ımage;
		}

		public IActionResult Index()
		{
			var imageList = _imageService.GetAll();
			var model = new GalleryIndexModel()
			{
				Images = imageList,
				SearcQuery = ""
			};
			return View(model);

		}

		
	
	}
}

KombniyAppAccount/Controllers/ImageController.cs
using KombniyAppAccount.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KombniyAppAccount.Controllers
{
	public class ImageController : Controller
	{
		public IActionResult Upload()
		{
			var model = new UploadImageModel();
			return View();
		}

		[HttpPost]
		public IActionResult UploadNewImage()
		{
			return Ok();
		}
	}
}

KombniyAppAccount/Controllers/StylingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KombniyAppAccount.Controllers
{
	public class StylingController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

KombniyAppAccount/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KombniyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link  rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css"/>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" >KombinyApp </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Galeri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Upload">Fotoraf yükleme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Styling" asp-action="Index">Styling Paketleri</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <ejs-scripts></ejs-scripts>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - KombinyApp - <a asp-area="" asp-controller="Home" asp-action="Index">ANA SAYFA</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>